server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-ecom-db
    username: postgres
    password: Abdullah2004*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  threads:
    virtual:
      enabled: true