spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-ecom-db
    username: postgres
    password: Abdullah2004*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  threads:
    virtual:
      enabled: true
  mail:
    host: "sandbox.smtp.mailtrap.io"
    port: 587
    username: "eb3d98eb8166d1"
    password: "c434d75778187a"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
        ssl:
          trust: "*"
springdoc:
  paths-to-match: /**